'use client'

import { forwardRef, useEffect, useState } from 'react'

interface PrintLayoutProps {
  children: React.ReactNode
  title?: string
  clinicName?: string
  clinicLogo?: string
  clinicAddress?: string
  clinicPhone?: string
  clinicEmail?: string
  watermark?: string
  showQRCode?: boolean
  qrCodeData?: string
  className?: string
}

const PrintLayout = forwardRef<HTMLDivElement, PrintLayoutProps>(({
  children,
  title = 'Pulse HMS',
  clinicName = 'Pulse HMS Clinic',
  clinicLogo,
  clinicAddress = '123 Medical Center, City, Country',
  clinicPhone = '+92 300 1234567',
  clinicEmail = 'info@pulsehms.com',
  watermark = 'Generated via Pulse HMS',
  showQRCode = false,
  qrCodeData,
  className = ''
}, ref) => {
  return (
    <div 
      ref={ref}
      className={`print-layout bg-white text-black ${className}`}
      style={{ 
        fontFamily: 'Roboto, Arial, sans-serif',
        lineHeight: '1.4'
      }}
    >
      {/* Print-specific styles */}
      <style jsx>{`
        @media print {
          .print-layout {
            width: 100% !important;
            margin: 0 !important;
            padding: 20px !important;
            background: white !important;
            color: black !important;
            font-size: 12px !important;
          }
          
          .print-header {
            border-bottom: 2px solid #333 !important;
            margin-bottom: 20px !important;
            padding-bottom: 15px !important;
          }
          
          .print-footer {
            border-top: 1px solid #ccc !important;
            margin-top: 20px !important;
            padding-top: 15px !important;
            font-size: 10px !important;
          }
          
          .watermark {
            position: fixed !important;
            top: 50% !important;
            left: 50% !important;
            transform: translate(-50%, -50%) rotate(-45deg) !important;
            opacity: 0.1 !important;
            font-size: 48px !important;
            color: #ccc !important;
            pointer-events: none !important;
            z-index: 1000 !important;
          }
          
          .no-print {
            display: none !important;
          }
        }
        
        @media screen {
          .print-layout {
            max-width: 800px;
            margin: 0 auto;
            padding: 40px;
            box-shadow: 0 0 20px rgba(0,0,0,0.1);
            border-radius: 8px;
          }
        }
      `}</style>

      {/* Watermark */}
      <div className="watermark">{watermark}</div>

      {/* Header */}
      <div className="print-header">
        <div className="flex justify-between items-start">
          <div className="flex items-center space-x-4">
            {clinicLogo && (
              <img 
                src={clinicLogo} 
                alt="Clinic Logo" 
                className="w-16 h-16 object-contain"
              />
            )}
            <div>
              <h1 className="text-2xl font-bold text-gray-900">{clinicName}</h1>
              <p className="text-sm text-gray-600">{clinicAddress}</p>
              <p className="text-sm text-gray-600">
                Phone: {clinicPhone} | Email: {clinicEmail}
              </p>
            </div>
          </div>
          
          {showQRCode && qrCodeData && (
            <div className="text-right">
              <QRCode 
                value={qrCodeData}
                size={80}
                level="M"
                className="border border-gray-300"
              />
              <p className="text-xs text-gray-500 mt-1">Scan for digital copy</p>
            </div>
          )}
        </div>
        
        {title && (
          <div className="mt-4">
            <h2 className="text-xl font-semibold text-gray-800 border-b border-gray-300 pb-2">
              {title}
            </h2>
          </div>
        )}
      </div>

      {/* Content */}
      <div className="print-content">
        {children}
      </div>

      {/* Footer */}
      <div className="print-footer">
        <div className="flex justify-between items-center text-gray-600">
          <div>
            <p className="text-xs">
              Generated on {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit'
              })}
            </p>
            <p className="text-xs">This document is digitally generated by Pulse HMS</p>
          </div>
          <div className="text-right">
            <p className="text-xs font-semibold">{clinicName}</p>
            <p className="text-xs">{clinicPhone}</p>
          </div>
        </div>
      </div>
    </div>
  )
})

PrintLayout.displayName = 'PrintLayout'

export default PrintLayout 